[build]
  command = "cd front && npm install && npm run build"
  publish = "front/out"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Next.js specific configuration
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/image/*"
  to = "/_next/image/:splat"
  status = 200

# Handle client-side routing - this should be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200