export const LOCATION = {  
    FRONTEND: 'FRONTEND',
    BACKEND: 'BACKEND',
    DATABASE: 'DATABASE',
    TOOLS: 'TOOLS',
    DATA: 'DATA',
    PROJECT: 'PROJECT',
};

export const SECTION ={
    HOME: 'HOME',
    TOOLS: 'TOOLS',
    FRONTEND: 'FRONTEND',
    BACKEND: 'BACKEND',
    DATABASE: 'DATABASE',
    DATA: 'DATA',
}